application: cs-253
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /lesson_3/blog/css/
  static_dir: /lesson_3/blog/css
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest


